# -*- coding: utf-8 -*-
"""python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NVlI32fAZgXrzi_01Ag9C79x3ax35Fq4
"""

class Human:
    #Humanクラスの初期化メソッド
    def __init__(self, name, age):
        self.name = name
        self.age = age

    #年齢が２０歳未満かチェック
    def checkadult(self):
        if self.age>=20 :
            print(f"{self.name}は大人です")
        else:
            print(f"{self.name}は大人ではありません")

# 人々の名前と年齢を格納した辞書
ages_dict = {"ichiro": 25, "jiro": 21, "saburo": 18, "siro": 17, "goro": 8}

#辞書内の各人物についてHumanクラスのインスタンスを作成し、大人かどうかチェック
for name, age in ages_dict.items():
    human = Human(name, age)
    human.checkadult()